### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by tonynguyenit18** [rubenkaiser/serverless-offline-eventBridge#36]
When `serverless-offline-eventBridge` receive a too large payload, we got this error
```bash
 PayloadTooLargeError: request entity too large
fi-serverless-local              |     at readStream (/app/node_modules/raw-body/index.js:155:17)
fi-serverless-local              |     at getRawBody (/app/node_modules/raw-body/index.js:108:12)
fi-serverless-local              |     at read (/app/node_modules/body-parser/lib/read.js:77:3)
fi-serverless-local              |     at jsonParser (/app/node_modules/body-parser/lib/types/json.js:135:5)
fi-serverless-local              |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
fi-serverless-local              |     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
fi-serverless-local              |     at /app/node_modules/express/lib/router/index.js:284:7
fi-serverless-local              |     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
fi-serverless-local              |     at next (/app/node_modules/express/lib/router/index.js:275:10)
fi-serverless-local              |     at cors (/app/node_modules/cors/lib/index.js:188:7)
fi-serverless-local              |     at /app/node_modules/cors/lib/index.js:224:17
fi-serverless-local              |     at originCallback (/app/node_modules/cors/lib/index.js:214:15)
fi-serverless-local              |     at /app/node_modules/cors/lib/index.js:219:13
fi-serverless-local              |     at optionsCallback (/app/node_modules/cors/lib/index.js:199:9)
fi-serverless-local              |     at corsMiddleware (/app/node_modules/cors/lib/index.js:204:7)
fi-serverless-local              |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
fi-serverless-local              |     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
fi-serverless-local              |     at /app/node_modules/express/lib/router/index.js:284:7
fi-serverless-local              |     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
fi-serverless-local              |     at next (/app/node_modules/express/lib/router/index.js:275:10)
fi-serverless-local              |     at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
fi-serverless-local              |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
fi-serverless-local              |     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
fi-serverless-local              |     at /app/node_modules/express/lib/router/index.js:284:7
fi-serverless-local              |     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
fi-serverless-local              |     at next (/app/node_modules/express/lib/router/index.js:275:10)
fi-serverless-local              |     at query (/app/node_modules/express/lib/middleware/query.js:45:5)
fi-serverless-local              |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
fi-serverless-local              |     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
fi-serverless-local              |     at /app/node_modules/express/lib/router/index.js:284:7
fi-serverless-local              |     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
fi-serverless-local              |     at next (/app/node_modules/express/lib/router/index.js:275:10)
fi-serverless-local              |     at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
fi-serverless-local              |     at Function.handle (/app/node_modules/express/lib/application.js:174:10)
fi-serverless-local              |     at Server.app (/app/node_modules/express/lib/express.js:39:9)
fi-serverless-local              |     at Server.emit (node:events:394:28)
fi-serverless-local              |     at Server.emit (node:domain:470:12)
fi-serverless-local              |     at parserOnIncoming (node:_http_server:924:12)
fi-serverless-local              |     at HTTPParser.parserOnHeadersComplete (node:_http_common:127:17)
```

I do debug myself I found it's likely from express.json limit size (currently "10mb") https://github.com/rubenkaiser/serverless-offline-eventBridge/blob/master/src/index.js#L131

Should we increase it or let it configurable?

I can give it a try if you are happy @rubenkaiser

**Comment by rubenkaiser** [comment]
The limit is indeed 10mb at the moment. This however should be 256kb as this is the limit that AWS describes (https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-putevent-size.html).

Therefore I think you should reconsider your implementation. However in the plugin it would be nice to be able to configure it yourselves. Have a go at it and create a PR. Thanks

**Comment by tonynguyenit18** [comment]
Hi @rubenkaiser 
You are right AWS eventbridge limit size is 256kb, And I also check my payload by calculating it https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-putevent-size.html, it less then 256kb.
=> My application work fine in AWS Eventbridge but it gets the issue with this plugin

=> So I guess express app in this plugin receives more than what we really publish.

Thanks. I'll create a PR soon.

**Comment by rubenkaiser** [comment]
You can install the new version now: `serverless-offline-aws-eventbridge@1.6.2`.

Thanks
