### ISSUE TITLE
Cannot find module 'serverless-offline/dist/lambda'

### ISSUE THREAD

**Issue by darbio** [rubenkaiser/serverless-offline-eventBridge#49]
When I add this dependency to a project and start the serverless with `sls offline start` I get an error stating `Cannot find module 'serverless-offline/dist/lambda'`. When I comment out `serverless-offline-eventBridge` in plugins the error goes away.

Expected behaviour would be for it to run.

Versions
```
Framework Core: 2.40.0 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.2
```

Package:
```
"esbuild": "^0.14.42",
"serverless": "^3.19.0",
"serverless-dynamodb-local": "^0.2.40",
"serverless-esbuild": "^1.30.0",
"serverless-offline": "^8.8.0",
"serverless-offline-aws-eventbridge": "^1.6.6",
"serverless-plugin-monorepo": "^0.10.0",
```

Output
```
Error: Cannot find module 'serverless-offline/dist/lambda'
Require stack:
- /fake/base/src/node_modules/serverless-offline-aws-eventbridge/src/index.js
- /fake/base/src/stacks/api/node_modules/serverless/lib/utils/import-module.js
- /fake/base/src/stacks/api/node_modules/serverless/lib/classes/plugin-manager.js
- /fake/base/src/stacks/api/node_modules/serverless/lib/serverless.js
- /fake/base/src/stacks/api/node_modules/serverless/scripts/serverless.js
- /fake/base/src/stacks/api/node_modules/serverless/bin/serverless.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/fake/base/src/node_modules/serverless-offline-aws-eventbridge/src/index.js:9:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (/fake/base/src/stacks/api/node_modules/serverless/lib/utils/import-module.js:5:12)
    at PluginManager.requireServicePlugin (/fake/base/src/stacks/api/node_modules/serverless/lib/classes/plugin-manager.js:171:14)
    at PluginManager.resolveServicePlugins (/fake/base/src/stacks/api/node_modules/serverless/lib/classes/plugin-manager.js:198:29)
    at async PluginManager.loadAllPlugins (/fake/base/src/stacks/api/node_modules/serverless/lib/classes/plugin-manager.js:136:36)
    at async Serverless.init (/fake/base/src/stacks/api/node_modules/serverless/lib/serverless.js:141:5)
    at async /fake/base/src/stacks/api/node_modules/serverless/scripts/serverless.js:591:7
```

serverless.yml
```
...
plugins:
  - serverless-esbuild
  - serverless-plugin-monorepo
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-offline-aws-eventbridge
```

**Comment by darbio** [comment]
A reinstall of `serverless-offline` fixed this. Closing.
